import mongoose from "mongoose";

const messageSchema = new mongoose.Schema({
  chatId: { type: mongoose.Schema.Types.ObjectId, ref: "Chat", required: true },
  userId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },

  // Message meta
  role: { type: String, enum: ["user", "assistant"], required: true },
  direction: { type: String, enum: ["incoming", "outgoing"], required: true },
  type: {
    type: String,
    enum: ["text", "image", "audio", "video"],
    default: "text",
  },
  content: { type: String },

  ai_provider: { type: String }, // if generated by AI
  tokens_used: { type: Number }, // for AI messages
  metadata: { type: Object }, // platform-specific data (ids, media urls, etc.)

  timestamp: { type: Date, default: Date.now },
});

const Message =
  mongoose.models.Message || mongoose.model("Message", messageSchema);
export default Message;
